# Generated by Django 5.1.5 on 2025-02-16 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('endpoint', models.CharField(max_length=50, unique=True)),
                ('method', models.CharField(choices=[('ANY', 'Any'), ('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete')], max_length=10)),
                ('response', models.TextField()),
                ('response_type', models.CharField(choices=[('TEXT', 'Text/Html'), ('JSON', 'Json')], max_length=5)),
                ('status_code', models.IntegerField(default=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EndpointUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('ANY', 'Any'), ('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete')], max_length=10)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endpoints.endpoint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
